package de.hysky.skyblocker.skyblock.tabhud.util;

import de.hysky.skyblocker.skyblock.item.HeadTextures;
import de.hysky.skyblocker.utils.ItemUtils;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;

/**
 * Stores convenient shorthands for common ItemStack definitions
 */
public class Ico {
	public static final ItemStack MAP = Items.FILLED_MAP.getDefaultInstance();
	public static final ItemStack NTAG = Items.NAME_TAG.getDefaultInstance();
	public static final ItemStack EMERALD = Items.EMERALD.getDefaultInstance();
	public static final ItemStack MAGMA_CREAM = Items.MAGMA_CREAM.getDefaultInstance();
	public static final ItemStack GEMSTONE = ItemUtils.createSkull(HeadTextures.GEMSTONE);
	public static final ItemStack CLOCK = Items.CLOCK.getDefaultInstance();
	public static final ItemStack DIA_SWORD = Items.DIAMOND_SWORD.getDefaultInstance();
	public static final ItemStack DBUSH = Items.DEAD_BUSH.getDefaultInstance();
	public static final ItemStack VILLAGER = Items.VILLAGER_SPAWN_EGG.getDefaultInstance();
	public static final ItemStack SPAWN_EGG = Items.GHAST_SPAWN_EGG.getDefaultInstance();
	public static final ItemStack GOLDEN_APPLE = Items.GOLDEN_APPLE.getDefaultInstance();
	public static final ItemStack COMPASS = Items.COMPASS.getDefaultInstance();
	public static final ItemStack SUGAR = Items.SUGAR.getDefaultInstance();
	public static final ItemStack IRON_HOE = Items.IRON_HOE.getDefaultInstance();
	public static final ItemStack GOLDEN_HOE = Items.GOLDEN_HOE.getDefaultInstance();
	public static final ItemStack GOLD = Items.GOLD_INGOT.getDefaultInstance();
	public static final ItemStack IRON = Items.IRON_INGOT.getDefaultInstance();
	public static final ItemStack BONE = Items.BONE.getDefaultInstance();
	public static final ItemStack SIGN = Items.OAK_SIGN.getDefaultInstance();
	public static final ItemStack FISH_ROD = Items.FISHING_ROD.getDefaultInstance();
	public static final ItemStack STONE_SWORD = Items.STONE_SWORD.getDefaultInstance();
	public static final ItemStack IRON_SWORD = Items.IRON_SWORD.getDefaultInstance();
	public static final ItemStack LANTERN = Items.LANTERN.getDefaultInstance();
	public static final ItemStack COOKIE = Items.COOKIE.getDefaultInstance();
	public static final ItemStack POTION = Items.POTION.getDefaultInstance();
	public static final ItemStack GOD_POTION = ItemUtils.createSkull(HeadTextures.GOD_POTION);
	public static final ItemStack S_POTION = Items.SPLASH_POTION.getDefaultInstance();
	public static final ItemStack BARRIER = Items.BARRIER.getDefaultInstance();
	public static final ItemStack PLAYER = Items.PLAYER_HEAD.getDefaultInstance();
	public static final ItemStack FAIRY_SOUL = ItemUtils.createSkull(HeadTextures.FAIRY_SOUL);
	public static final ItemStack WATER = Items.WATER_BUCKET.getDefaultInstance();
	public static final ItemStack LEATHER = Items.LEATHER.getDefaultInstance();
	public static final ItemStack MITHRIL = Items.PRISMARINE_CRYSTALS.getDefaultInstance();
	public static final ItemStack REDSTONE = Items.REDSTONE.getDefaultInstance();
	public static final ItemStack CAMPFIRE = Items.CAMPFIRE.getDefaultInstance();
	public static final ItemStack STRING = Items.STRING.getDefaultInstance();
	public static final ItemStack WITHER = Items.WITHER_SKELETON_SKULL.getDefaultInstance();
	public static final ItemStack FLESH = Items.ROTTEN_FLESH.getDefaultInstance();
	public static final ItemStack MUTTON = Items.MUTTON.getDefaultInstance();
	public static final ItemStack DRAGON = Items.DRAGON_HEAD.getDefaultInstance();
	public static final ItemStack DIAMOND = Items.DIAMOND.getDefaultInstance();
	public static final ItemStack ICE = Items.ICE.getDefaultInstance();
	public static final ItemStack CHEST = Items.CHEST.getDefaultInstance();
	public static final ItemStack COMMAND = Items.COMMAND_BLOCK.getDefaultInstance();
	public static final ItemStack SKULL = Items.SKELETON_SKULL.getDefaultInstance();
	public static final ItemStack BOOK = Items.WRITABLE_BOOK.getDefaultInstance();
	public static final ItemStack FURNACE = Items.FURNACE.getDefaultInstance();
	public static final ItemStack CHESTPLATE = Items.IRON_CHESTPLATE.getDefaultInstance();
	public static final ItemStack L_CHESTPLATE = Items.LEATHER_CHESTPLATE.getDefaultInstance();
	public static final ItemStack B_ROD = Items.BLAZE_ROD.getDefaultInstance();
	public static final ItemStack B_POWDER = Items.BLAZE_POWDER.getDefaultInstance();
	public static final ItemStack BOW = Items.BOW.getDefaultInstance();
	public static final ItemStack COPPER = Items.COPPER_INGOT.getDefaultInstance();
	public static final ItemStack NETHERITE_UPGRADE_ST = Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE.getDefaultInstance();
	public static final ItemStack COMPOSTER = Items.COMPOSTER.getDefaultInstance();
	public static final ItemStack SAPLING = Items.OAK_SAPLING.getDefaultInstance();
	public static final ItemStack SEEDS = Items.WHEAT_SEEDS.getDefaultInstance();
	public static final ItemStack LODESTONE = Items.LODESTONE.getDefaultInstance();
	public static final ItemStack STONE_PICKAXE = Items.STONE_PICKAXE.getDefaultInstance();
	public static final ItemStack IRON_PICKAXE = Items.IRON_PICKAXE.getDefaultInstance();
	public static final ItemStack NETHER_STAR = Items.NETHER_STAR.getDefaultInstance();
	public static final ItemStack HEART_OF_THE_SEA = Items.HEART_OF_THE_SEA.getDefaultInstance();
	public static final ItemStack EXPERIENCE_BOTTLE = Items.EXPERIENCE_BOTTLE.getDefaultInstance();
	public static final ItemStack PINK_DYE = Items.PINK_DYE.getDefaultInstance();
	public static final ItemStack LIME_DYE = Items.LIME_DYE.getDefaultInstance();
	public static final ItemStack GRAY_DYE = Items.GRAY_DYE.getDefaultInstance();
	public static final ItemStack ENCHANTED_BOOK = Items.ENCHANTED_BOOK.getDefaultInstance();
	public static final ItemStack SPIDER_EYE = Items.SPIDER_EYE.getDefaultInstance();
	public static final ItemStack PACKED_ICE = Items.PACKED_ICE.getDefaultInstance();
	public static final ItemStack JUNGLE_SAPLING = Items.JUNGLE_SAPLING.getDefaultInstance();
	public static final ItemStack ENCHANTING_TABLE = Items.ENCHANTING_TABLE.getDefaultInstance();
	public static final ItemStack BREWING_STAND = Items.BREWING_STAND.getDefaultInstance();
	public static final ItemStack CRAFTING_TABLE = Items.CRAFTING_TABLE.getDefaultInstance();
	public static final ItemStack PAINTING = Items.PAINTING.getDefaultInstance();
	public static final ItemStack E_PEARL = Items.ENDER_PEARL.getDefaultInstance();
	public static final ItemStack FEATHER = Items.FEATHER.getDefaultInstance();
	public static final ItemStack E_CHEST = Items.ENDER_CHEST.getDefaultInstance();
	public static final ItemStack MYCELIUM = Items.MYCELIUM.getDefaultInstance();
	public static final ItemStack SALMON_BUCKET = Items.SALMON_BUCKET.getDefaultInstance();
	public static final ItemStack TROPICAL_FISH_BUCKET = Items.TROPICAL_FISH_BUCKET.getDefaultInstance();
	public static final ItemStack STRIPPED_SPRUCE_WOOD = Items.STRIPPED_SPRUCE_WOOD.getDefaultInstance();
	public static final ItemStack MANGROVE_LOG = Items.MANGROVE_LOG.getDefaultInstance();
	public static final ItemStack OMINOUS_BOTTLE = Items.OMINOUS_BOTTLE.getDefaultInstance();
	public static final ItemStack CATACOMBS = ItemUtils.createSkull(HeadTextures.CATACOMBS);
	public static final ItemStack MADDOX_BATPHONE = ItemUtils.createSkull(HeadTextures.MADDOX_BATPHONE);
	public static final ItemStack LEAD = Items.LEAD.getDefaultInstance();
}
