package de.hysky.skyblocker.skyblock.tabhud.util;

import de.hysky.skyblocker.skyblock.item.HeadTextures;
import de.hysky.skyblocker.utils.ItemUtils;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;

/**
 * Stores convenient shorthands for common ItemStack definitions
 */
public class Ico {
	public static final ItemStack MAP = Items.FILLED_MAP.getDefaultStack();
	public static final ItemStack NTAG = Items.NAME_TAG.getDefaultStack();
	public static final ItemStack EMERALD = Items.EMERALD.getDefaultStack();
	public static final ItemStack MAGMA_CREAM = Items.MAGMA_CREAM.getDefaultStack();
	public static final ItemStack GEMSTONE = ItemUtils.createSkull(HeadTextures.GEMSTONE);
	public static final ItemStack CLOCK = Items.CLOCK.getDefaultStack();
	public static final ItemStack DIA_SWORD = Items.DIAMOND_SWORD.getDefaultStack();
	public static final ItemStack DBUSH = Items.DEAD_BUSH.getDefaultStack();
	public static final ItemStack VILLAGER = Items.VILLAGER_SPAWN_EGG.getDefaultStack();
	public static final ItemStack SPAWN_EGG = Items.GHAST_SPAWN_EGG.getDefaultStack();
	public static final ItemStack GOLDEN_APPLE = Items.GOLDEN_APPLE.getDefaultStack();
	public static final ItemStack COMPASS = Items.COMPASS.getDefaultStack();
	public static final ItemStack SUGAR = Items.SUGAR.getDefaultStack();
	public static final ItemStack IRON_HOE = Items.IRON_HOE.getDefaultStack();
	public static final ItemStack GOLDEN_HOE = Items.GOLDEN_HOE.getDefaultStack();
	public static final ItemStack GOLD = Items.GOLD_INGOT.getDefaultStack();
	public static final ItemStack IRON = Items.IRON_INGOT.getDefaultStack();
	public static final ItemStack BONE = Items.BONE.getDefaultStack();
	public static final ItemStack SIGN = Items.OAK_SIGN.getDefaultStack();
	public static final ItemStack FISH_ROD = Items.FISHING_ROD.getDefaultStack();
	public static final ItemStack STONE_SWORD = Items.STONE_SWORD.getDefaultStack();
	public static final ItemStack IRON_SWORD = Items.IRON_SWORD.getDefaultStack();
	public static final ItemStack LANTERN = Items.LANTERN.getDefaultStack();
	public static final ItemStack COOKIE = Items.COOKIE.getDefaultStack();
	public static final ItemStack POTION = Items.POTION.getDefaultStack();
	public static final ItemStack GOD_POTION = ItemUtils.createSkull(HeadTextures.GOD_POTION);
	public static final ItemStack S_POTION = Items.SPLASH_POTION.getDefaultStack();
	public static final ItemStack BARRIER = Items.BARRIER.getDefaultStack();
	public static final ItemStack PLAYER = Items.PLAYER_HEAD.getDefaultStack();
	public static final ItemStack FAIRY_SOUL = ItemUtils.createSkull(HeadTextures.FAIRY_SOUL);
	public static final ItemStack WATER = Items.WATER_BUCKET.getDefaultStack();
	public static final ItemStack LEATHER = Items.LEATHER.getDefaultStack();
	public static final ItemStack MITHRIL = Items.PRISMARINE_CRYSTALS.getDefaultStack();
	public static final ItemStack REDSTONE = Items.REDSTONE.getDefaultStack();
	public static final ItemStack CAMPFIRE = Items.CAMPFIRE.getDefaultStack();
	public static final ItemStack STRING = Items.STRING.getDefaultStack();
	public static final ItemStack WITHER = Items.WITHER_SKELETON_SKULL.getDefaultStack();
	public static final ItemStack FLESH = Items.ROTTEN_FLESH.getDefaultStack();
	public static final ItemStack MUTTON = Items.MUTTON.getDefaultStack();
	public static final ItemStack DRAGON = Items.DRAGON_HEAD.getDefaultStack();
	public static final ItemStack DIAMOND = Items.DIAMOND.getDefaultStack();
	public static final ItemStack ICE = Items.ICE.getDefaultStack();
	public static final ItemStack CHEST = Items.CHEST.getDefaultStack();
	public static final ItemStack COMMAND = Items.COMMAND_BLOCK.getDefaultStack();
	public static final ItemStack SKULL = Items.SKELETON_SKULL.getDefaultStack();
	public static final ItemStack BOOK = Items.WRITABLE_BOOK.getDefaultStack();
	public static final ItemStack FURNACE = Items.FURNACE.getDefaultStack();
	public static final ItemStack CHESTPLATE = Items.IRON_CHESTPLATE.getDefaultStack();
	public static final ItemStack L_CHESTPLATE = Items.LEATHER_CHESTPLATE.getDefaultStack();
	public static final ItemStack B_ROD = Items.BLAZE_ROD.getDefaultStack();
	public static final ItemStack B_POWDER = Items.BLAZE_POWDER.getDefaultStack();
	public static final ItemStack BOW = Items.BOW.getDefaultStack();
	public static final ItemStack COPPER = Items.COPPER_INGOT.getDefaultStack();
	public static final ItemStack NETHERITE_UPGRADE_ST = Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE.getDefaultStack();
	public static final ItemStack COMPOSTER = Items.COMPOSTER.getDefaultStack();
	public static final ItemStack SAPLING = Items.OAK_SAPLING.getDefaultStack();
	public static final ItemStack SEEDS = Items.WHEAT_SEEDS.getDefaultStack();
	public static final ItemStack LODESTONE = Items.LODESTONE.getDefaultStack();
	public static final ItemStack STONE_PICKAXE = Items.STONE_PICKAXE.getDefaultStack();
	public static final ItemStack IRON_PICKAXE = Items.IRON_PICKAXE.getDefaultStack();
	public static final ItemStack NETHER_STAR = Items.NETHER_STAR.getDefaultStack();
	public static final ItemStack HEART_OF_THE_SEA = Items.HEART_OF_THE_SEA.getDefaultStack();
	public static final ItemStack EXPERIENCE_BOTTLE = Items.EXPERIENCE_BOTTLE.getDefaultStack();
	public static final ItemStack PINK_DYE = Items.PINK_DYE.getDefaultStack();
	public static final ItemStack LIME_DYE = Items.LIME_DYE.getDefaultStack();
	public static final ItemStack GRAY_DYE = Items.GRAY_DYE.getDefaultStack();
	public static final ItemStack ENCHANTED_BOOK = Items.ENCHANTED_BOOK.getDefaultStack();
	public static final ItemStack SPIDER_EYE = Items.SPIDER_EYE.getDefaultStack();
	public static final ItemStack PACKED_ICE = Items.PACKED_ICE.getDefaultStack();
	public static final ItemStack JUNGLE_SAPLING = Items.JUNGLE_SAPLING.getDefaultStack();
	public static final ItemStack ENCHANTING_TABLE = Items.ENCHANTING_TABLE.getDefaultStack();
	public static final ItemStack BREWING_STAND = Items.BREWING_STAND.getDefaultStack();
	public static final ItemStack CRAFTING_TABLE = Items.CRAFTING_TABLE.getDefaultStack();
	public static final ItemStack PAINTING = Items.PAINTING.getDefaultStack();
	public static final ItemStack E_PEARL = Items.ENDER_PEARL.getDefaultStack();
	public static final ItemStack FEATHER = Items.FEATHER.getDefaultStack();
	public static final ItemStack E_CHEST = Items.ENDER_CHEST.getDefaultStack();
	public static final ItemStack MYCELIUM = Items.MYCELIUM.getDefaultStack();
	public static final ItemStack SALMON_BUCKET = Items.SALMON_BUCKET.getDefaultStack();
	public static final ItemStack TROPICAL_FISH_BUCKET = Items.TROPICAL_FISH_BUCKET.getDefaultStack();
	public static final ItemStack STRIPPED_SPRUCE_WOOD = Items.STRIPPED_SPRUCE_WOOD.getDefaultStack();
	public static final ItemStack MANGROVE_LOG = Items.MANGROVE_LOG.getDefaultStack();
	public static final ItemStack OMINOUS_BOTTLE = Items.OMINOUS_BOTTLE.getDefaultStack();
}
