package de.hysky.skyblocker.skyblock.tabhud.util;

import de.hysky.skyblocker.skyblock.item.HeadTextures;
import de.hysky.skyblocker.utils.FlexibleItemStack;
import de.hysky.skyblocker.utils.ItemUtils;
import net.minecraft.world.item.Items;

/**
 * Stores convenient shorthands for common FlexibleItemStack definitions
 */
public class Ico {
	public static final FlexibleItemStack MAP = new FlexibleItemStack(Items.FILLED_MAP);
	public static final FlexibleItemStack NTAG = new FlexibleItemStack(Items.NAME_TAG);
	public static final FlexibleItemStack EMERALD = new FlexibleItemStack(Items.EMERALD);
	public static final FlexibleItemStack MAGMA_CREAM = new FlexibleItemStack(Items.MAGMA_CREAM);
	public static final FlexibleItemStack GEMSTONE = ItemUtils.createSkull(HeadTextures.GEMSTONE);
	public static final FlexibleItemStack CLOCK = new FlexibleItemStack(Items.CLOCK);
	public static final FlexibleItemStack DIA_SWORD = new FlexibleItemStack(Items.DIAMOND_SWORD);
	public static final FlexibleItemStack DBUSH = new FlexibleItemStack(Items.DEAD_BUSH);
	public static final FlexibleItemStack VILLAGER = new FlexibleItemStack(Items.VILLAGER_SPAWN_EGG);
	public static final FlexibleItemStack SPAWN_EGG = new FlexibleItemStack(Items.GHAST_SPAWN_EGG);
	public static final FlexibleItemStack GOLDEN_APPLE = new FlexibleItemStack(Items.GOLDEN_APPLE);
	public static final FlexibleItemStack COMPASS = new FlexibleItemStack(Items.COMPASS);
	public static final FlexibleItemStack SUGAR = new FlexibleItemStack(Items.SUGAR);
	public static final FlexibleItemStack IRON_HOE = new FlexibleItemStack(Items.IRON_HOE);
	public static final FlexibleItemStack GOLDEN_HOE = new FlexibleItemStack(Items.GOLDEN_HOE);
	public static final FlexibleItemStack GOLD = new FlexibleItemStack(Items.GOLD_INGOT);
	public static final FlexibleItemStack IRON = new FlexibleItemStack(Items.IRON_INGOT);
	public static final FlexibleItemStack BONE = new FlexibleItemStack(Items.BONE);
	public static final FlexibleItemStack SIGN = new FlexibleItemStack(Items.OAK_SIGN);
	public static final FlexibleItemStack FISH_ROD = new FlexibleItemStack(Items.FISHING_ROD);
	public static final FlexibleItemStack STONE_SWORD = new FlexibleItemStack(Items.STONE_SWORD);
	public static final FlexibleItemStack IRON_SWORD = new FlexibleItemStack(Items.IRON_SWORD);
	public static final FlexibleItemStack LANTERN = new FlexibleItemStack(Items.LANTERN);
	public static final FlexibleItemStack COOKIE = new FlexibleItemStack(Items.COOKIE);
	public static final FlexibleItemStack POTION = new FlexibleItemStack(Items.POTION);
	public static final FlexibleItemStack GOD_POTION = ItemUtils.createSkull(HeadTextures.GOD_POTION);
	public static final FlexibleItemStack S_POTION = new FlexibleItemStack(Items.SPLASH_POTION);
	public static final FlexibleItemStack BARRIER = new FlexibleItemStack(Items.BARRIER);
	public static final FlexibleItemStack RED_CONCRETE = new FlexibleItemStack(Items.RED_CONCRETE);
	public static final FlexibleItemStack POISONOUS_POTATO = new FlexibleItemStack(Items.POISONOUS_POTATO);
	public static final FlexibleItemStack PLAYER = new FlexibleItemStack(Items.PLAYER_HEAD);
	public static final FlexibleItemStack FAIRY_SOUL = ItemUtils.createSkull(HeadTextures.FAIRY_SOUL);
	public static final FlexibleItemStack WATER = new FlexibleItemStack(Items.WATER_BUCKET);
	public static final FlexibleItemStack LEATHER = new FlexibleItemStack(Items.LEATHER);
	public static final FlexibleItemStack MITHRIL = new FlexibleItemStack(Items.PRISMARINE_CRYSTALS);
	public static final FlexibleItemStack REDSTONE = new FlexibleItemStack(Items.REDSTONE);
	public static final FlexibleItemStack CAMPFIRE = new FlexibleItemStack(Items.CAMPFIRE);
	public static final FlexibleItemStack STRING = new FlexibleItemStack(Items.STRING);
	public static final FlexibleItemStack WITHER = new FlexibleItemStack(Items.WITHER_SKELETON_SKULL);
	public static final FlexibleItemStack FLESH = new FlexibleItemStack(Items.ROTTEN_FLESH);
	public static final FlexibleItemStack MUTTON = new FlexibleItemStack(Items.MUTTON);
	public static final FlexibleItemStack DRAGON = new FlexibleItemStack(Items.DRAGON_HEAD);
	public static final FlexibleItemStack DIAMOND = new FlexibleItemStack(Items.DIAMOND);
	public static final FlexibleItemStack ICE = new FlexibleItemStack(Items.ICE);
	public static final FlexibleItemStack CHEST = new FlexibleItemStack(Items.CHEST);
	public static final FlexibleItemStack COMMAND = new FlexibleItemStack(Items.COMMAND_BLOCK);
	public static final FlexibleItemStack SKULL = new FlexibleItemStack(Items.SKELETON_SKULL);
	public static final FlexibleItemStack BOOK = new FlexibleItemStack(Items.WRITABLE_BOOK);
	public static final FlexibleItemStack FURNACE = new FlexibleItemStack(Items.FURNACE);
	public static final FlexibleItemStack CHESTPLATE = new FlexibleItemStack(Items.IRON_CHESTPLATE);
	public static final FlexibleItemStack L_CHESTPLATE = new FlexibleItemStack(Items.LEATHER_CHESTPLATE);
	public static final FlexibleItemStack B_ROD = new FlexibleItemStack(Items.BLAZE_ROD);
	public static final FlexibleItemStack B_POWDER = new FlexibleItemStack(Items.BLAZE_POWDER);
	public static final FlexibleItemStack BOW = new FlexibleItemStack(Items.BOW);
	public static final FlexibleItemStack COPPER = new FlexibleItemStack(Items.COPPER_INGOT);
	public static final FlexibleItemStack NETHERITE_UPGRADE_ST = new FlexibleItemStack(Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE);
	public static final FlexibleItemStack COMPOSTER = new FlexibleItemStack(Items.COMPOSTER);
	public static final FlexibleItemStack SAPLING = new FlexibleItemStack(Items.OAK_SAPLING);
	public static final FlexibleItemStack SEEDS = new FlexibleItemStack(Items.WHEAT_SEEDS);
	public static final FlexibleItemStack LODESTONE = new FlexibleItemStack(Items.LODESTONE);
	public static final FlexibleItemStack STONE_PICKAXE = new FlexibleItemStack(Items.STONE_PICKAXE);
	public static final FlexibleItemStack IRON_PICKAXE = new FlexibleItemStack(Items.IRON_PICKAXE);
	public static final FlexibleItemStack NETHER_STAR = new FlexibleItemStack(Items.NETHER_STAR);
	public static final FlexibleItemStack HEART_OF_THE_SEA = new FlexibleItemStack(Items.HEART_OF_THE_SEA);
	public static final FlexibleItemStack EXPERIENCE_BOTTLE = new FlexibleItemStack(Items.EXPERIENCE_BOTTLE);
	public static final FlexibleItemStack PINK_DYE = new FlexibleItemStack(Items.PINK_DYE);
	public static final FlexibleItemStack LIME_DYE = new FlexibleItemStack(Items.LIME_DYE);
	public static final FlexibleItemStack GRAY_DYE = new FlexibleItemStack(Items.GRAY_DYE);
	public static final FlexibleItemStack ENCHANTED_BOOK = new FlexibleItemStack(Items.ENCHANTED_BOOK);
	public static final FlexibleItemStack SPIDER_EYE = new FlexibleItemStack(Items.SPIDER_EYE);
	public static final FlexibleItemStack PACKED_ICE = new FlexibleItemStack(Items.PACKED_ICE);
	public static final FlexibleItemStack JUNGLE_SAPLING = new FlexibleItemStack(Items.JUNGLE_SAPLING);
	public static final FlexibleItemStack ENCHANTING_TABLE = new FlexibleItemStack(Items.ENCHANTING_TABLE);
	public static final FlexibleItemStack BREWING_STAND = new FlexibleItemStack(Items.BREWING_STAND);
	public static final FlexibleItemStack CRAFTING_TABLE = new FlexibleItemStack(Items.CRAFTING_TABLE);
	public static final FlexibleItemStack PAINTING = new FlexibleItemStack(Items.PAINTING);
	public static final FlexibleItemStack E_PEARL = new FlexibleItemStack(Items.ENDER_PEARL);
	public static final FlexibleItemStack FEATHER = new FlexibleItemStack(Items.FEATHER);
	public static final FlexibleItemStack E_CHEST = new FlexibleItemStack(Items.ENDER_CHEST);
	public static final FlexibleItemStack MYCELIUM = new FlexibleItemStack(Items.MYCELIUM);
	public static final FlexibleItemStack SALMON_BUCKET = new FlexibleItemStack(Items.SALMON_BUCKET);
	public static final FlexibleItemStack TROPICAL_FISH_BUCKET = new FlexibleItemStack(Items.TROPICAL_FISH_BUCKET);
	public static final FlexibleItemStack STRIPPED_SPRUCE_WOOD = new FlexibleItemStack(Items.STRIPPED_SPRUCE_WOOD);
	public static final FlexibleItemStack MANGROVE_LOG = new FlexibleItemStack(Items.MANGROVE_LOG);
	public static final FlexibleItemStack OMINOUS_BOTTLE = new FlexibleItemStack(Items.OMINOUS_BOTTLE);
	public static final FlexibleItemStack CATACOMBS = ItemUtils.createSkull(HeadTextures.CATACOMBS);
	public static final FlexibleItemStack MADDOX_BATPHONE = ItemUtils.createSkull(HeadTextures.MADDOX_BATPHONE);
	public static final FlexibleItemStack LEAD = new FlexibleItemStack(Items.LEAD);
	public static final FlexibleItemStack HOPPER = new FlexibleItemStack(Items.HOPPER);
	public static final FlexibleItemStack WHEAT = new FlexibleItemStack(Items.WHEAT);
	public static final FlexibleItemStack CARROT = new FlexibleItemStack(Items.CARROT);
	public static final FlexibleItemStack POTATO = new FlexibleItemStack(Items.POTATO);
	public static final FlexibleItemStack PUMPKIN = new FlexibleItemStack(Items.PUMPKIN);
	public static final FlexibleItemStack MELON_SLICE = new FlexibleItemStack(Items.MELON_SLICE);
	public static final FlexibleItemStack RED_MUSHROOM = new FlexibleItemStack(Items.RED_MUSHROOM);
	public static final FlexibleItemStack CACTUS = new FlexibleItemStack(Items.CACTUS);
	public static final FlexibleItemStack SUGAR_CANE = new FlexibleItemStack(Items.SUGAR_CANE);
	public static final FlexibleItemStack NETHER_WART = new FlexibleItemStack(Items.NETHER_WART);
	public static final FlexibleItemStack COCOA_BEANS = new FlexibleItemStack(Items.COCOA_BEANS);
	public static final FlexibleItemStack SUNFLOWER = new FlexibleItemStack(Items.SUNFLOWER);
	public static final FlexibleItemStack BLUE_ORCHID = new FlexibleItemStack(Items.BLUE_ORCHID);
	public static final FlexibleItemStack ROSE_BUSH = new FlexibleItemStack(Items.ROSE_BUSH);
}
