name: Crash Report
description: Create a report to inform us of a constant crash
labels: [crash]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this crash report!
        
        Before continuing to make the issue, please make sure there are no similar issues on [the issue tracker](https://github.com/SkyblockerMod/Skyblocker/issues). If there are, consider contributing your information in there instead!
        
        Also, make sure you are using the latest version of the mod! If not, try updating to see if it resolves your issue.
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running? If you do not know what version you are using, look in the bottom left corner of the main menu in game.
      options:
        - "1.20.4"
    validations:
      required: true
  - type: input
    id: skyblocker-version
    attributes:
      label: Skyblocker Version
      description: What version of Skyblocker are you running? Every part is important! If you do not know what version you are using, look at the file name in your "mods" folder.
      placeholder: ex. skyblocker-1.17.0+1.20.4.jar
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Provide information on how to reproduce this game crash. You can either fill this section in like the example below or do something else -- just make sure your instructions are minimal and clear, as other people will need to be able to replicate your issue.
      placeholder: |
        1. Place a Redstone Lamp in front of a Redstone Repeater
        2. Use a Lever to activate the Redstone Repeater
        3. Game Crashes
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Crash Report file and latest.log
      description: |
        Upload your crash report file and latest.log as an attachment to this issue (drag-and-drop) or to a service such as GitHub Gist (paste a link). This information is critical in resolving your issue!
        
        Tip: Messages like "Exit code 0" from your launcher are not what you're looking for. If your launcher does not provide a button to view the most recent crash report, check your game's "crash-reports" folder for the most recent crash report file.
        
        This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        ---- Minecraft Crash Report ----
        // Don't be sad, have a hug! <3
        
        Time: 2023-08-16 11:56:19
        Description: Unexpected error
        
        java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because the return value of "java.util.HashMap.get(Object)" is null
          at de.hysky.skyblocker.skyblock.dungeon.secrets.Room.<init>(Room.java:80)
          at de.hysky.skyblocker.skyblock.dungeon.secrets.DungeonSecrets.newRoom(DungeonSecrets.java:297)
          at de.hysky.skyblocker.skyblock.dungeon.secrets.DungeonSecrets.update(DungeonSecrets.java:263)
          at de.hysky.skyblocker.utils.Scheduler$CyclicTask.run(Scheduler.java:102)
          at de.hysky.skyblocker.utils.Scheduler$ScheduledTask.run(Scheduler.java:120)
          at de.hysky.skyblocker.utils.Scheduler.runTask(Scheduler.java:88)
          at de.hysky.skyblocker.utils.Scheduler.tick(Scheduler.java:76)
          at de.hysky.skyblocker.SkyblockerMod.tick(SkyblockerMod.java:116)
          at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
          at net.minecraft.class_310.handler$ble000$fabric-lifecycle-events-v1$onEndTick(class_310.java:11022)
          at net.minecraft.class_310.method_1574(class_310.java:1957)
          at net.minecraft.class_310.method_1523(class_310.java:1181)
          at net.minecraft.class_310.method_1514(class_310.java:802)
          at net.minecraft.client.main.Main.main(Main.java:250)
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide any additional information or context which may be relevant to the issue. This is optional
    validations:
      required: false
