name: Client Game Test

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - master
      - bleeding-edge
    paths-ignore:
      - 'src/main/resources/assets/skyblocker/lang/**'
      - 'CHANGELOG.md'
      - 'FEATURES.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'src/main/resources/assets/skyblocker/lang/**'
      - 'CHANGELOG.md'
      - 'FEATURES.md'
      - 'README.md'
env:
  REF_NAME: ${{ github.ref_name }}
  PR_NUMBER: ${{ github.event.number }}
  PR_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  client_game_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      - name: Run client gametest with Gradle
        run: ./gradlew runClientGametest
      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        with:
          name: Test Screenshots
          path: run/screenshots
